# Generated by Django 2.1.1 on 2018-09-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_auto_20180919_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='carId',
            field=models.IntegerField(),
        ),
    ]
