# Generated by Django 2.1.1 on 2018-09-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_auto_20180919_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='carId',
            field=models.DateField(),
        ),
    ]
