# Generated by Django 2.1.1 on 2018-10-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_auto_20180919_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='carId',
            field=models.IntegerField(),
        ),
    ]
