# Generated by Django 2.1.1 on 2018-10-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_auto_20181022_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='returnDate',
            field=models.DateField(),
        ),
    ]
